# Generated by Django 5.2.7 on 2025-10-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteamAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(help_text='Логин Steam', max_length=150)),
                ('shared_secret', models.CharField(blank=True, help_text='shared_secret (Base64/hex/Base32)', max_length=200)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
